title: My Blog
description: Live Jekyll site by widowmaker101
url: "https://widowmaker101.github.io"
baseurl: "/myblog"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

author:
  name: widowmaker101
  bio: Developer | Creator | Learner

minimal_mistakes_skin: "air"
